### ISSUE TITLE
Using DBngin - error: mysql: No such file or directory

### ISSUE THREAD

**Issue by nathangross** [aaemnnosttv/wp-cli-valet-command#78] opened 2021-08-26 19:29 UTC
Laravel Valet docs now seemingly suggest using DBngin for local database management. That's how I'm currently set up. If I run `wp valet new bedrock --project=bedrock` I get the following `Error: Failed to get current SQL modes. Reason: env: mysql: No such file or directory`

I'm curious if it is possible to get this to work properly with DBngin. 

Thanks in advance!

**Comment by aaemnnosttv** [comment] 2021-08-28 08:35
Hey there, I see what the problem is now. It looks like DBngin does not use the same location for the Unix socket `/tmp/mysql.sock`. Instead, for me it seems to use the configured port # as part of the socket name: e.g. `/tmp/mysql_3306.sock` (which makes sense because DBngin is designed to run multiple DB instances simultaneously). This fails because mysql is trying to use `/tmp/mysql.sock` for whatever reason. When using the Homebrew-installed mysql/mariadb, this socket is in this location so it works.

WP CLI defaults to `localhost` as the DB host which is always interpreted as "use the unix socket" to connect rather than TCP. We have an issue on the repo here to allow customizing this when creating a new site in #73 but if you change your `DB_HOST` in `wp-config.php` to `127.0.0.1`, it should work with DBngine just fine, although until that issue is done, you wouldn't be able to _create_ a new site with the Valet command using DBngine without additional changes to your wp-cli config. You can create/update your [wp-cli config](https://make.wordpress.org/cli/handbook/references/config/#config-files) file to set the default `dbhost` to `127.0.0.1` although this would have to be done for the **core command** (e.g. `core install` – [see the readme](https://github.com/aaemnnosttv/wp-cli-valet-command#configuring-alternate-defaults) for an example of how this works although this example is for the `valet new` command but the same approach works for any other) 

I hope that makes sense. See [this excellent write up about mysql connections](https://serversforhackers.com/c/mysql-network-security) for more information. This is ultimately not really an issue with the command itself though (other than what's already covered by #73) so I'm going to close this one out. Hopefully this information helps anyone else running into the same problem though. Cheers!

**Closed by aaemnnosttv** 2021-08-28 08:35 UTC
