### ISSUE TITLE
wp valet database

### ISSUE THREAD

**Issue by aryanrajcom** [aaemnnosttv/wp-cli-valet-command#71] opened 2021-01-13 16:02 UTC
Hi, my valet install with wp-cli-valet-command no longer works on Big Sur. However, I was able to re-install and make laravel website work. but no WordPress. this error is giving me a headache. 

```
Don't go anywhere, this should only take a second...
Error: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

I would like to know if it is possible to get the database files of older websites so i just  export them and import using a different tool. Previously, I was able to login with localhost ip with username root and blank password. I no longer can connect.

I can see the websites files but not know where the database files are.

Thanks.

**Comment by aaemnnosttv** [comment] 2021-09-07 21:18
One other possibility here is that the database server unix socket isn't in the usual location (as noted in the error message). If you've changed your local environment at all lately this could be related.

This likely isn't a problem with the valet command though so I'll close this for now but feel free to provide some additional information and maybe we can figure out what the problem is.

**Closed by aaemnnosttv** 2021-09-07 21:18 UTC
