### ISSUE TITLE
wp valet new site Error establishing connection

### ISSUE THREAD

**Issue by vady-patel** [aaemnnosttv/wp-cli-valet-command#72] opened 2021-02-08 04:28 UTC
After updating my Mac OS to Big Sur, I am experiencing this `Error: Error establishing a database connection.` whenever I run wp valet new sitename command. If I run wp cli info command this is what I get. I have also tried to connect db using Table plus and the connection is successful. How do I resolve the db error?

Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php/8.0.1_1/bin/php
PHP version:	8.0.1
php.ini used:	/usr/local/etc/php/8.0/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/vadypatel/Documents/Sites
WP-CLI packages dir:	/Users/vadypatel/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0

**Comment by aaemnnosttv** [comment] 2021-04-05 05:22
Hi there,

You might need to make sure that your credentials used by the command are correct. Try running the `wp valet new` command with the `--debug` flag to see the full (verbose) output. This will show you all the underlying commands.

There isn't quite enough information to say for sure what the problem is though. One thing you might check is the hostname used for mysql. If it's `localhost`, try `127.0.0.1` and see if that works since mysql treats them differently.

**Comment by aaemnnosttv** [comment] 2021-09-07 21:22
Looking at your wp-cli info that you provided I don't see anything that would cause the command to fail.

Please try updating your dependencies to the latest and try again. Closing for now but feel free to provide more information if you're still having a problem!

**Closed by aaemnnosttv** 2021-09-07 21:22 UTC
